### ISSUE TITLE
Wither Skeleton Spawning Bug

### ISSUE THREAD

**Issue by Keridos** [SgtPunishment/Soul-Shards-The-Old-Ways-1.7.10#19]
A wither skeleton spawner sometimes spawns skeletons, which it should not do.

**Comment by SgtPunishment** [comment]
I'm trying to replicate this issue but I don't seem I can, could you expand, for example what kind of setup are you using? is it in the overworld, the nether or the end?

**Comment by Keridos** [comment]
It is in a spatial storage cell from AppliedEnergistics 2.

**Comment by SgtPunishment** [comment]
I will look into this, may take a while

**Comment by SgtPunishment** [comment]
Okay, I spent all morning attempting to replicate this bug and so far I've been unable to, are you using a public mod pack or a private mod pack?

**Comment by Keridos** [comment]
It is a private one, but I can give you a copy per pm on curseforge, if you want.

**Comment by SgtPunishment** [comment]
I think that would be best so I can figure out what's causing this problem as I spent about an hour just spawning wither skeletons inside a spatial storage cell and not one came out as a normal skeleton

**Comment by Keridos** [comment]
Sent you a PM on curseforge.

**Comment by SgtPunishment** [comment]
I have tried and tried again, but I cannot recreate this bug.
