### ISSUE TITLE
[Feature Request] Configurable blacklist

### ISSUE THREAD

**Issue by InfinityRaider** [SgtPunishment/Soul-Shards-The-Old-Ways-1.7.10#26]
Is it possible to implement a configurable blacklist for certain entities? Because this would be a useful feature in certain cases.

**Comment by SgtPunishment** [comment]
I know the previous version had a black list option but moze didn't readd it when he overhauled the mod (This is built on his original code) I will discuss with my team.

**Comment by SgtPunishment** [comment]
Sorry to keep you waiting for a response, but our lead developer is currently MIA, I will look over the old code and see if it can be added back in.

**Comment by InfinityRaider** [comment]
Okay thanks, its not really a pressing matter, but it would be nice to have some balancing options.

**Comment by SgtPunishment** [comment]
Okay, I've started work on re adding the functionality, so far I'm having trouble with grabbing the list from the entity mapper and parsing it into a black list function to generate the black list file (The file itself generates fine, but it's empty)
